version: 2.1

jobs:
  hello-world-job:
    docker:
      - image: cimg/base:current
    steps:
      - run: echo "Hello, World!"
      - run: echo "Hello, CircleCI!"

workflows:
  hello-world-workflow:
    jobs:
      - hello-world-job
